// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) Contributors to the OpenEXR Project.

// This file is auto-generated by the configure step

#ifndef INCLUDED_OPENEXR_INTERNAL_CONFIG_H
#define INCLUDED_OPENEXR_INTERNAL_CONFIG_H 1

#pragma once

//
// Define and set to 1 if the target system is a Darwin-based system
// (e.g., OS X).
//

/* #undef OPENEXR_IMF_HAVE_DARWIN */

//
// Define and set to 1 if the target system has a complete <iomanip>
// implementation, specifically if it supports the std::right
// formatter.
//

#define OPENEXR_IMF_HAVE_COMPLETE_IOMANIP 1

//
// Define if we can use sysconf(_SC_NPROCESSORS_ONLN) to get CPU count
//

// #define OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN 1

//
// Define if we can support GCC style inline asm with AVX instructions
//

// #define OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX 1

#endif // INCLUDED_OPENEXR_INTERNAL_CONFIG_H
